# Generated by Django 6.0.4 on 2026-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(default=2025, max_length=10),
            preserve_default=False,
        ),
    ]
